In [1]:
from array import *
x=array('i',[1,2,3,4])

In [2]:
x

array('i', [1, 2, 3, 4])

In [4]:
x[:]

array('i', [1, 2, 3, 4])

In [15]:
print(x[2])
x.append(7)
x


3


array('i', [1, 2, 3, 4, 7])

In [14]:
x.remove(7)

In [23]:
Y=np.array([[1,2,3],[4,5,6]])

In [29]:
print(Y)
print(Y.itemsize)
print(Y.nbytes)

[[1 2 3]
 [4 5 6]]
4
24


In [19]:
X=np.ones([4,2,2],dtype='int32')

In [20]:
print(X.shape )
X.ndim

(4, 2, 2)


3

In [21]:
X

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [22]:
X.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [5]:
np.full([2,2],99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [14]:
x=np.zeros([2,3,3,2])
x

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [22]:
print(x.ndim)
print(x.shape)

4
(2, 3, 3, 2)


In [16]:
x.shape

(2, 3, 3, 2)

In [30]:
a=np.array([[1,2,3,4,5,6,7,8]])
a=a.reshape([4,2])
print(a)
print(np.full_like(a.shape,4))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[4 4]


In [28]:
np.random.randint(7,size=(3,3))

array([[6, 1, 2],
       [5, 2, 6],
       [3, 0, 0]])

In [25]:
np.random.sample(a.shape)

array([3.46260118e-01, 2.70148132e-04, 5.78570917e-01, 3.25488009e-01])

In [40]:
ar=np.array([[1,2,3]])
r=np.repeat(ar,3,axis=0)
r

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [41]:
np.linspace(-2,2,num=5)

array([-2., -1.,  0.,  1.,  2.])

In [42]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825]])

In [46]:
st=np.array([[1,2,3],[4,5,6]])
st

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.min(st,axis=1)

array([1, 4])

In [50]:
v1=np.array([1,2,3])
v2=np.array([4,5,3])
np.vstack([v1,v2])


array([[1, 2, 3],
       [4, 5, 3]])

In [51]:
nx=np.random.randint(9,size=(3,3))

In [52]:
nx

array([[2, 5, 5],
       [0, 8, 7],
       [3, 5, 8]])

In [53]:
nx>0

array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [60]:
np.any(nx>0,axis=0)

array([ True,  True,  True])

In [62]:
np.all(nx>0,axis=0)

array([False,  True,  True])

In [8]:
s1=pd.Series([1,2,3,4],['USA','Germany','USSR','Japan'])
s2=pd.Series([1,2,5,4],['USA','Germany','Italy','Japan'])

In [5]:
s1+s2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [17]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [32]:
arr1=np.arange(10)

In [33]:
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [36]:
print(arr1.min())
arr1.max()

0


9

In [48]:
a=np.arange(6)
a=a.reshape([2,3])
b=np.arange(6)
b=a.reshape([3,2])
print(a,end='\n')
print(b)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [43]:
np.matmul(a,b)

array([[10, 13],
       [28, 40]])

In [44]:
np.dot(a,b)

array([[10, 13],
       [28, 40]])

In [45]:
np.log(a)

array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791]])

In [46]:
a.argmax()

5

In [50]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [51]:
np.exp(a)

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [52]:
a.diagonal()

array([0, 4])

In [55]:
np.any(a>0)

True

In [56]:
np.all(a>0)

False

In [59]:
z=np.matrix('1,2,3;4,5,6;7,8,9')

In [61]:
np.linalg.det(z)

6.66133814775094e-16